sudo: required
services:
  - docker

# before_install:
#   - docker build -t eraarby/react-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run eraarby/react-test npm run test -- --converage

# after_success:
before_install:
  - docker build -t eraarby/multi-client ./client
  - docker build -t eraarby/multi-nginx ./nginx
  - docker build -t eraarby/multi-server ./server
  - docker build -t eraarby/multi-worker ./worker
# Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take these images and push them to docker hub
  - docker push eraarby/multi-client
  - docker push eraarby/multi-nginx
  - docker push eraarby/multi-server
  - docker push eraarby/multi-worker

deploy:
  provider: azure_web_apps
  username: multidocker\$multidocker       # If AZURE_WA_USERNAME isn't set
  password: AyShsTNRYak8wGytdgjxheZYCDkif7tYfD1yDG116JMg4879wQGpqwScstC3   # If AZURE_WA_PASSWORD isn't set
  site: multidocker       # If AZURE_WA_SITE isn't set
  # slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set

